import { StyleSheet } from 'react-native';

export const driverStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#f8f7f3',
  },
  content: {
    padding: 16,
    paddingBottom: 40,
  },
  centered: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    backgroundColor: '#f8f7f3',
  },
  loadingText: {
    marginTop: 12,
    fontSize: 16,
    color: '#374151',
  },
  heroCard: {
    backgroundColor: '#ffffff',
    borderRadius: 28,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    padding: 20,
    marginBottom: 14,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  heroCardCompact: {
    backgroundColor: '#ffffff',
    borderRadius: 28,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    padding: 18,
    marginBottom: 14,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  heroTopRow: {
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    gap: 12,
  },
  heroIdentityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
  },
  heroIconWrap: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fef3c7',
    marginRight: 14,
    borderWidth: 1,
    borderColor: '#fde68a',
  },
  heroIcon: {
    fontSize: 20,
    fontWeight: '800',
    color: '#111827',
  },
  heroTextWrap: {
    flex: 1,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: '#111827',
    marginBottom: 6,
  },
  sectionTitleCompact: {
    fontSize: 18,
    fontWeight: '800',
    color: '#111827',
    marginBottom: 3,
  },
  heroPanel: {
    backgroundColor: '#f4efe2',
    borderRadius: 24,
    padding: 18,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#eadfbc',
  },
  heroPanelTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  heroEyebrow: {
    color: '#9a6b16',
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.7,
    marginBottom: 8,
  },
  heroHeadline: {
    color: '#111827',
    fontSize: 24,
    fontWeight: '800',
    lineHeight: 30,
    marginBottom: 6,
  },
  heroSubtitleStrong: {
    color: '#6b7280',
    fontSize: 14,
    lineHeight: 20,
  },
  heroStatusBadge: {
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
  },
  heroStatusBadgeOnline: {
    backgroundColor: '#e7f6ec',
    borderColor: '#b7dfc4',
  },
  heroStatusBadgeOffline: {
    backgroundColor: '#fff3dd',
    borderColor: '#efd4a1',
  },
  heroStatusBadgeText: {
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  heroStatusBadgeTextOnline: {
    color: '#166534',
  },
  heroStatusBadgeTextOffline: {
    color: '#9a6b16',
  },
  heroDivider: {
    height: 1,
    backgroundColor: '#e5dbc0',
    marginVertical: 16,
  },
  heroMetricsRow: {
    flexDirection: 'row',
    gap: 10,
  },
  heroMetricCard: {
    flex: 1,
    borderRadius: 18,
    backgroundColor: '#fffaf0',
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: '#efe3bf',
  },
  heroMetricLabel: {
    color: '#6b7280',
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 5,
  },
  heroMetricValue: {
    color: '#111827',
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 4,
  },
  heroMetricHint: {
    color: '#6b7280',
    fontSize: 12,
    lineHeight: 17,
  },
  heroFooterNote: {
    color: '#6b7280',
    fontSize: 13,
    lineHeight: 19,
    marginTop: 2,
    paddingHorizontal: 2,
  },
  heroSubtitle: {
    color: '#6b7280',
    fontSize: 15,
    lineHeight: 22,
  },
  availabilityWrap: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  driverStatusTopRow: {
    marginBottom: 12,
  },
  heroIdentityRowCompact: {
    width: '100%',
  },
  driverAvailabilityStrip: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#fde68a',
    borderRadius: 20,
    backgroundColor: '#fffaf0',
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 14,
  },
  driverAvailabilityTextWrap: {
    flex: 1,
    marginRight: 12,
  },
  driverAvailabilityValue: {
    color: '#111827',
    fontSize: 16,
    fontWeight: '800',
  },
  availabilityLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#6b7280',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    marginBottom: 4,
  },
  heroStatsRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 2,
  },
  heroStatPill: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#f3e7b3',
    backgroundColor: '#fffaf0',
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  heroStatLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#6b7280',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    marginBottom: 4,
  },
  heroStatValue: {
    fontSize: 14,
    fontWeight: '700',
    color: '#111827',
  },
  heroStatHint: {
    marginTop: 4,
    color: '#6b7280',
    fontSize: 12,
  },
  helperText: {
    color: '#6b7280',
    fontSize: 13,
    marginBottom: 8,
  },
  card: {
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 28,
    padding: 18,
    backgroundColor: '#ffffff',
    marginBottom: 14,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  cardTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  cardTitleIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#f3f4f6',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  cardTitleIcon: {
    color: '#111827',
    fontWeight: '800',
    fontSize: 14,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#111827',
  },
  innerCard: {
    borderWidth: 1,
    borderColor: '#e5e7eb',
    padding: 14,
    marginTop: 10,
    borderRadius: 16,
    backgroundColor: '#fcfcfc',
  },
  tripStageCard: {
    borderWidth: 1,
    borderColor: '#fde68a',
    borderRadius: 18,
    padding: 14,
    backgroundColor: '#fff8db',
    marginTop: 8,
    marginBottom: 12,
  },
  tripStageTitle: {
    color: '#111827',
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 6,
  },
  tripStageSubtitle: {
    color: '#4b5563',
    fontSize: 14,
    lineHeight: 20,
  },
  paymentStatusCard: {
    borderWidth: 1,
    borderRadius: 18,
    padding: 14,
    marginBottom: 12,
  },
  paymentStatusCardPaid: {
    borderColor: '#bbf7d0',
    backgroundColor: '#f0fdf4',
  },
  paymentStatusCardPending: {
    borderColor: '#fde68a',
    backgroundColor: '#fffbeb',
  },
  paymentStatusEyebrow: {
    color: '#6b7280',
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    marginBottom: 5,
  },
  paymentStatusTitle: {
    color: '#111827',
    fontSize: 17,
    fontWeight: '800',
    marginBottom: 6,
  },
  paymentStatusSubtitle: {
    color: '#4b5563',
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '600',
  },
  tripInfoGrid: {
    flexDirection: 'column',
    gap: 10,
    marginBottom: 12,
  },
  tripInfoBlock: {
    width: '100%',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 16,
    padding: 12,
    backgroundColor: '#fbfbfa',
  },
  tripInfoBlockWide: {
    width: '100%',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 16,
    padding: 12,
    backgroundColor: '#fbfbfa',
  },
  detailText: {
    color: '#374151',
    fontSize: 14,
    marginBottom: 6,
  },
  cardBodyTitle: {
    color: '#6b7280',
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    marginBottom: 4,
    marginTop: 4,
  },
  cardBodyValue: {
    color: '#111827',
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 6,
  },
  map: {
    width: '100%',
    height: 240,
    borderRadius: 14,
    marginBottom: 12,
  },
  mapPreviewCard: {
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 22,
    padding: 16,
    backgroundColor: '#fbfbfa',
    marginBottom: 12,
  },
  mapPreviewTitle: {
    color: '#111827',
    fontSize: 15,
    fontWeight: '800',
    marginBottom: 8,
  },
  dispatchTitleWrap: {
    flex: 1,
  },
  dispatchTitleSubtext: {
    color: '#6b7280',
    fontSize: 12,
    marginTop: 2,
  },
  priorityHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 10,
    marginBottom: 8,
  },
  prioritySubtitle: {
    color: '#6b7280',
    fontSize: 12,
    lineHeight: 18,
    maxWidth: 220,
  },
  priorityBadge: {
    borderRadius: 999,
    backgroundColor: '#fef3c7',
    borderWidth: 1,
    borderColor: '#fde68a',
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  priorityBadgeText: {
    color: '#92400e',
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  rideInfoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 4,
    marginBottom: 4,
  },
  rideInfoCell: {
    width: '47%',
    borderWidth: 1,
    borderColor: '#ece7d5',
    backgroundColor: '#fffef8',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  rideInfoLabel: {
    color: '#6b7280',
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    marginBottom: 4,
  },
  rideInfoValue: {
    color: '#111827',
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 18,
  },
  statusBanner: {
    borderWidth: 1,
    borderColor: '#fde68a',
    borderRadius: 18,
    padding: 13,
    backgroundColor: '#fff8db',
    marginBottom: 12,
  },
  statusTitle: {
    fontWeight: '700',
    color: '#111827',
    marginBottom: 4,
  },
  urgentBanner: {
    borderWidth: 1,
    borderColor: '#fde68a',
    borderRadius: 18,
    padding: 14,
    backgroundColor: '#fffbeb',
    marginBottom: 12,
  },
  urgentTitle: {
    color: '#92400e',
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 6,
  },
  urgentCountdown: {
    color: '#b45309',
    fontSize: 13,
    fontWeight: '700',
  },
  actionButton: {
    backgroundColor: '#111827',
    paddingVertical: 14,
    borderRadius: 16,
    alignItems: 'center',
    marginTop: 10,
  },
  actionButtonText: {
    color: '#ffffff',
    fontWeight: '700',
    fontSize: 15,
  },
  actionButtonDisabled: {
    opacity: 0.6,
  },
  secondaryButton: {
    borderWidth: 1,
    borderColor: '#d1d5db',
    backgroundColor: '#fbfbfa',
    paddingVertical: 14,
    borderRadius: 16,
    alignItems: 'center',
    marginTop: 10,
  },
  secondaryButtonText: {
    color: '#1f2937',
    fontWeight: '700',
    fontSize: 15,
  },
  dangerButton: {
    borderWidth: 1,
    borderColor: '#fecaca',
    backgroundColor: '#fff7f7',
    paddingVertical: 14,
    borderRadius: 16,
    alignItems: 'center',
    marginTop: 10,
  },
  dangerButtonText: {
    color: '#991b1b',
    fontWeight: '700',
    fontSize: 15,
  },
  secondaryButtonDisabled: {
    opacity: 0.6,
  },
  showMoreButton: {
    marginTop: 12,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#ffffff',
    borderRadius: 14,
    alignItems: 'center',
    paddingVertical: 13,
  },
  showMoreButtonText: {
    color: '#111827',
    fontSize: 14,
    fontWeight: '700',
  },
  listHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 14,
    marginBottom: 8,
  },
  listHeaderTitle: {
    color: '#111827',
    fontSize: 15,
    fontWeight: '800',
  },
  listHeaderCount: {
    color: '#6b7280',
    fontSize: 12,
    fontWeight: '700',
  },
  metaRow: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
    marginTop: 8,
  },
  metaPill: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#fde68a',
    backgroundColor: '#fffaf0',
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  metaPillText: {
    color: '#374151',
    fontSize: 12,
    fontWeight: '700',
  },
  emptyStateCard: {
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 18,
    padding: 16,
    backgroundColor: '#f9fafb',
    marginTop: 10,
  },
  emptyStateTitle: {
    color: '#111827',
    fontSize: 16,
    fontWeight: '800',
    marginBottom: 6,
  },
  message: {
    marginBottom: 12,
    color: '#1d4ed8',
    fontWeight: '600',
    textAlign: 'center',
    paddingHorizontal: 16,
  },
  globalBanner: {
    borderRadius: 18,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderWidth: 1,
    marginBottom: 12,
  },
  infoBanner: {
    backgroundColor: '#eff6ff',
    borderColor: '#bfdbfe',
  },
  successBanner: {
    backgroundColor: '#f0fdf4',
    borderColor: '#bbf7d0',
  },
  warningBanner: {
    backgroundColor: '#fff7ed',
    borderColor: '#fed7aa',
  },
  globalBannerTitle: {
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    color: '#1f2937',
    marginBottom: 4,
  },
  globalBannerText: {
    color: '#111827',
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '600',
  },
  dispatchModeCard: {
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 18,
    backgroundColor: '#f9fafb',
    padding: 14,
    marginTop: 12,
  },
  dispatchModeTitle: {
    color: '#111827',
    fontSize: 16,
    fontWeight: '800',
    marginBottom: 6,
  },
  refreshMetaText: {
    color: '#6b7280',
    fontSize: 12,
    marginTop: 2,
  },
  dispatchRideCard: {
    marginTop: 12,
    borderRadius: 20,
    backgroundColor: '#fcfcfa',
  },
  dispatchRideCardSelected: {
    borderColor: '#fde68a',
    backgroundColor: '#fffef8',
  },
  dispatchRideHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 8,
  },
  dispatchRideTextWrap: {
    flex: 1,
  },
  rideMiniStatsRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 2,
    marginBottom: 4,
  },
  rideMiniStat: {
    flex: 1,
    borderRadius: 14,
    backgroundColor: '#f8f6ef',
    borderWidth: 1,
    borderColor: '#ede8da',
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  rideMiniStatLabel: {
    color: '#6b7280',
    fontSize: 10,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    marginBottom: 3,
  },
  rideMiniStatValue: {
    color: '#111827',
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 17,
  },
  closestBadge: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#fde68a',
    backgroundColor: '#fff8db',
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  closestBadgeText: {
    color: '#92400e',
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
});
