import { StyleSheet } from 'react-native';

export const driverStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#f3f4f6',
  },
  content: {
    padding: 16,
    paddingBottom: 40,
  },
  centered: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    backgroundColor: '#f3f4f6',
  },
  loadingText: {
    marginTop: 12,
    fontSize: 16,
    color: '#374151',
  },
  heroCard: {
    backgroundColor: '#ffffff',
    borderRadius: 28,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    padding: 20,
    marginBottom: 14,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 4 },
    elevation: 5,
  },
  heroTopRow: {
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    gap: 12,
  },
  heroIdentityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
  },
  heroIconWrap: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f3f4f6',
    marginRight: 14,
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  heroIcon: {
    fontSize: 20,
    fontWeight: '800',
    color: '#111827',
  },
  heroTextWrap: {
    flex: 1,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: '#111827',
    marginBottom: 6,
  },
  heroSubtitle: {
    color: '#6b7280',
    fontSize: 14,
    lineHeight: 21,
  },
  availabilityWrap: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  availabilityLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#374151',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    marginBottom: 4,
  },
  heroStatsRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 18,
  },
  heroStatPill: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#f9fafb',
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  heroStatLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#6b7280',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    marginBottom: 4,
  },
  heroStatValue: {
    fontSize: 14,
    fontWeight: '700',
    color: '#111827',
  },
  heroStatHint: {
    marginTop: 4,
    color: '#6b7280',
    fontSize: 12,
  },
  helperText: {
    color: '#6b7280',
    fontSize: 13,
    marginBottom: 8,
  },
  card: {
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 28,
    padding: 18,
    backgroundColor: '#ffffff',
    marginBottom: 14,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 4 },
    elevation: 5,
  },
  cardTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  cardTitleIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#f3f4f6',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  cardTitleIcon: {
    color: '#111827',
    fontWeight: '800',
    fontSize: 14,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#111827',
  },
  innerCard: {
    borderWidth: 1,
    borderColor: '#e5e7eb',
    padding: 14,
    marginTop: 10,
    borderRadius: 16,
    backgroundColor: '#fcfcfc',
  },
  tripStageCard: {
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 18,
    padding: 14,
    backgroundColor: '#f9fafb',
    marginTop: 8,
    marginBottom: 12,
  },
  tripStageTitle: {
    color: '#111827',
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 6,
  },
  tripStageSubtitle: {
    color: '#4b5563',
    fontSize: 14,
    lineHeight: 20,
  },
  tripInfoGrid: {
    flexDirection: 'column',
    gap: 10,
    marginBottom: 12,
  },
  tripInfoBlock: {
    width: '100%',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 16,
    padding: 12,
    backgroundColor: '#fcfcfc',
  },
  tripInfoBlockWide: {
    width: '100%',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 16,
    padding: 12,
    backgroundColor: '#fcfcfc',
  },
  detailText: {
    color: '#374151',
    fontSize: 14,
    marginBottom: 6,
  },
  cardBodyTitle: {
    color: '#6b7280',
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    marginBottom: 4,
    marginTop: 4,
  },
  cardBodyValue: {
    color: '#111827',
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 6,
  },
  map: {
    width: '100%',
    height: 240,
    borderRadius: 14,
    marginBottom: 12,
  },
  mapPreviewCard: {
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 18,
    padding: 14,
    backgroundColor: '#f9fafb',
    marginBottom: 12,
  },
  mapPreviewTitle: {
    color: '#111827',
    fontSize: 14,
    fontWeight: '800',
    marginBottom: 8,
  },
  statusBanner: {
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 16,
    padding: 12,
    backgroundColor: '#f9fafb',
    marginBottom: 12,
  },
  statusTitle: {
    fontWeight: '700',
    color: '#111827',
    marginBottom: 4,
  },
  urgentBanner: {
    borderWidth: 1,
    borderColor: '#fde68a',
    borderRadius: 18,
    padding: 14,
    backgroundColor: '#fffbeb',
    marginBottom: 12,
  },
  urgentTitle: {
    color: '#92400e',
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 6,
  },
  urgentCountdown: {
    color: '#b45309',
    fontSize: 13,
    fontWeight: '700',
  },
  actionButton: {
    backgroundColor: '#111827',
    paddingVertical: 14,
    borderRadius: 14,
    alignItems: 'center',
    marginTop: 10,
  },
  actionButtonText: {
    color: '#ffffff',
    fontWeight: '700',
    fontSize: 15,
  },
  actionButtonDisabled: {
    opacity: 0.6,
  },
  secondaryButton: {
    borderWidth: 1,
    borderColor: '#d1d5db',
    backgroundColor: '#f9fafb',
    paddingVertical: 14,
    borderRadius: 14,
    alignItems: 'center',
    marginTop: 10,
  },
  secondaryButtonText: {
    color: '#1f2937',
    fontWeight: '700',
    fontSize: 15,
  },
  secondaryButtonDisabled: {
    opacity: 0.6,
  },
  showMoreButton: {
    marginTop: 12,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#ffffff',
    borderRadius: 14,
    alignItems: 'center',
    paddingVertical: 13,
  },
  showMoreButtonText: {
    color: '#111827',
    fontSize: 14,
    fontWeight: '700',
  },
  metaRow: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
    marginTop: 8,
  },
  metaPill: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#ffffff',
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  metaPillText: {
    color: '#374151',
    fontSize: 12,
    fontWeight: '700',
  },
  emptyStateCard: {
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 18,
    padding: 16,
    backgroundColor: '#f9fafb',
    marginTop: 10,
  },
  emptyStateTitle: {
    color: '#111827',
    fontSize: 16,
    fontWeight: '800',
    marginBottom: 6,
  },
  message: {
    marginBottom: 12,
    color: '#1d4ed8',
    fontWeight: '600',
    textAlign: 'center',
    paddingHorizontal: 16,
  },
  globalBanner: {
    borderRadius: 18,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderWidth: 1,
    marginBottom: 12,
  },
  infoBanner: {
    backgroundColor: '#eff6ff',
    borderColor: '#bfdbfe',
  },
  successBanner: {
    backgroundColor: '#f0fdf4',
    borderColor: '#bbf7d0',
  },
  warningBanner: {
    backgroundColor: '#fff7ed',
    borderColor: '#fed7aa',
  },
  globalBannerTitle: {
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    color: '#1f2937',
    marginBottom: 4,
  },
  globalBannerText: {
    color: '#111827',
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '600',
  },
  dispatchModeCard: {
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 18,
    backgroundColor: '#f9fafb',
    padding: 14,
    marginTop: 12,
  },
  dispatchModeTitle: {
    color: '#111827',
    fontSize: 16,
    fontWeight: '800',
    marginBottom: 6,
  },
  refreshMetaText: {
    color: '#6b7280',
    fontSize: 12,
    marginTop: 2,
  },
});
